[versions]
kotlin-plugin = "2.1.21"
intellij-platform-plugin = "2.10.4"
apollo = "5.0.0-alpha.3"
grammarkit-plugin = "2022.3.2.2"
changelog-plugin = "2.2.1"
sqlite-jdbc = "3.43.2.0"
apollo-normalizedcache = "1.0.0-alpha.3"
slf4j = "2.0.17"
google-testparameterinjector = "1.11"
cdimascio-dotenv = "6.4.1"
atlassian-commonmark = "0.17.0"

# XXX Do update the supported versions in the README.md, and in docs/source/testing/android-studio-plugin.mdx file when updating these values!
# See https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html for insight into build numbers and IntelliJ Platform versions.
# See also https://blog.jetbrains.com/platform/2025/11/intellij-platform-2025-3-what-plugin-developers-should-know/
sinceBuild = "252"

# Corresponds to AS Otter 2025.2.1 -> https://plugins.jetbrains.com/docs/intellij/android-studio-releases-list.html
# and https://developer.android.com/studio/archive (more up to date)
# See also https://plugins.jetbrains.com/docs/intellij/android-studio.html
intellij-platform-version = "2025.2.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-plugin" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform-plugin" }
intellij-platform-module = { id = "org.jetbrains.intellij.platform.module", version.ref = "intellij-platform-plugin" }
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }
grammarkit = { id = "org.jetbrains.grammarkit", version.ref = "grammarkit-plugin" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog-plugin" }

[libraries]
apollo-annotations = { group = "com.apollographql.apollo", name = "apollo-annotations", version.ref = "apollo" }
apollo-api = { group = "com.apollographql.apollo", name = "apollo-api", version.ref = "apollo" }
apollo-runtime = { group = "com.apollographql.apollo", name = "apollo-runtime", version.ref = "apollo" }
apollo-gradle-plugin = { group = "com.apollographql.apollo", name = "apollo-gradle-plugin", version.ref = "apollo" }
apollo-ast = { group = "com.apollographql.apollo", name = "apollo-ast", version.ref = "apollo" }
apollo-tooling = { group = "com.apollographql.apollo", name = "apollo-tooling", version.ref = "apollo" }
apollo-compiler = { group = "com.apollographql.apollo", name = "apollo-compiler", version.ref = "apollo" }
apollo-normalized-cache-sqlite-classic = { group = "com.apollographql.apollo", name = "apollo-normalized-cache-sqlite", version.ref = "apollo" }
apollo-normalized-cache-sqlite-new = { group = "com.apollographql.cache", name = "normalized-cache-sqlite", version.ref = "apollo-normalizedcache" }
sqlite-jdbc = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite-jdbc" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
google-testparameterinjector = { group = "com.google.testparameterinjector", name = "test-parameter-injector", version.ref = "google-testparameterinjector" }
cdimascio-dotenv = { group = "io.github.cdimascio", name = "dotenv-kotlin", version.ref = "cdimascio-dotenv" }
atlassian-commonmark = { group = "com.atlassian.commonmark", name = "commonmark", version.ref = "atlassian-commonmark" }
